@host = http://localhost:8090
@base_url = api/v1/orders
@customer_id = 5
@order_id = 49
### Create Order
POST {{host}}/{{base_url}} HTTP/1.1
content-type: application/json

{
  "customer_id": {{customer_id}},
  "order_total": 100
}

### Cancel Order
DELETE {{host}}/{{base_url}}/{{order_id}} HTTP/1.1